ffi.enable=preload
opcache.preload=/app/vendor/godaddy/asherah/preload.php
; Set this to either a native library file or a directory containing libasherah_ffi.so.
env[ASHERAH_PHP_NATIVE]=/app/vendor/godaddy/asherah/native/linux-x64
