[package]
name = "asherah-bench"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]
members = []

[dependencies]
anyhow = "1.0"
criterion = { version = "0.5", features = ["html_reports"] }
libloading = "0.8"
once_cell = "1.19"
rand = "0.8"

[build-dependencies]
anyhow = "1.0"

[[bench]]
name = "ffi"
harness = false
