AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 25

Metrics/ClassLength:
  Max: 200

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
