name: "Benchmark: Memory (in-memory hot-cache)"

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  benchmark:
    uses: ./.github/workflows/benchmark-setup.yml
    with:
      bench_mode: memory
