name: napi-prebuild

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [18, 20]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - uses: dtolnay/rust-toolchain@stable
      - name: Install @napi-rs/cli
        run: npm install --global @napi-rs/cli
      - name: Build core crates
        run: cargo build --workspace --exclude asherah-py --exclude asherah-java
      - name: Build asherah-node prebuild
        working-directory: asherah-node
        run: |
          npm install
          npm run build:release
          npm run prepublishOnly
      - name: Run roundtrip test
        working-directory: asherah-node
        run: npm test
      - name: Upload artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: asherah-node-${{ matrix.os }}-node${{ matrix.node }}
          path: |
            asherah-node/npm/**
